// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDiagnostic } from "./WorkflowDiagnostic";
import type { WorkflowSummary } from "./WorkflowSummary";

export type WorkflowListResponse = { data: Array<WorkflowSummary>,
/**
 * Source-local discovery failures. A malformed document does not hide an
 * independent valid workflow from another source.
 */
diagnostics: Array<WorkflowDiagnostic>, };
