// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source encoding for a user-, project-, or plugin-owned workflow document.
 */
export type WorkflowDocumentFormat = "json" | "yaml";
