// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution engine selected by a `zuno.workflow/v1` document.
 */
export type WorkflowEngine = "graph/v1" | "javascript/v1" | "node-worker/v1";
