// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Start one exact workflow revision. `runId` is client supplied so a retry
 * after a lost response is idempotent. Reusing it with different args or a
 * different digest must fail closed.
 */
export type WorkflowStartParams = { runId: string, workflowId: string,
/**
 * Must match `WorkflowSummary.executableDigest`, preventing a document or
 * external script change between discovery and execution.
 */
expectedDigest: string, parentThreadId: string, args: JsonValue, };
