// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { WorkflowDocumentFormat } from "./WorkflowDocumentFormat";
import type { WorkflowSummary } from "./WorkflowSummary";

export type WorkflowReadResponse = { workflow: WorkflowSummary, format: WorkflowDocumentFormat,
/**
 * Exact source text. Keeping the text preserves YAML comments and makes
 * the digest independently verifiable by clients.
 */
document: string,
/**
 * Parsed definition for clients that do not need source-level editing.
 */
definition: JsonValue, };
