// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDiagnostic } from "./WorkflowDiagnostic";
import type { WorkflowSummary } from "./WorkflowSummary";

export type WorkflowValidateResponse = { valid: boolean, workflow: WorkflowSummary | null, diagnostics: Array<WorkflowDiagnostic>, };
