// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowEngine } from "./WorkflowEngine";
import type { WorkflowScope } from "./WorkflowScope";
import type { WorkflowSourceIdentity } from "./WorkflowSourceIdentity";

/**
 * A discovered and validated workflow. Zuno does not reserve names for
 * built-in business workflows; every entry comes from a discoverable source.
 */
export type WorkflowSummary = {
/**
 * Opaque registry selector. Callers must not derive this from the name.
 */
workflowId: string, identity: WorkflowSourceIdentity,
/**
 * Digest of all executable material. For `scriptFile` workflows this
 * binds both the document and resolved script bytes.
 */
executableDigest: string, description: string | null, engine: WorkflowEngine, scope: WorkflowScope, };
