// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type WorkflowListParams = {
/**
 * Working directories used for project and plugin discovery. Empty means
 * the app-server process working directory.
 */
cwds?: Array<AbsolutePathBuf>,
/**
 * Re-read configured roots instead of accepting a registry cache hit.
 */
forceReload?: boolean, };
