// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discovery authority that supplied a workflow. This is provenance, not a
 * precedence promise; `workflowId` remains the opaque selector.
 */
export type WorkflowScope = "user" | "project" | "plugin";
