// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRunRecord } from "./WorkflowRunRecord";

export type WorkflowStartResponse = {
/**
 * The request returns once the durable run is accepted, not when it ends.
 */
run: WorkflowRunRecord, };
