// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDocumentFormat } from "./WorkflowDocumentFormat";

/**
 * Validate an arbitrary document without installing it or mutating discovery
 * roots. The source id is only provenance for diagnostics and digesting.
 */
export type WorkflowValidateParams = { sourceId: string, format: WorkflowDocumentFormat, document: string, };
