// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { WorkflowCallStatus } from "./WorkflowCallStatus";

/**
 * One engine-to-host call in the durable ledger. The request digest allows a
 * recovered engine to detect divergent replay before dispatching a side effect.
 */
export type WorkflowCallRecord = { callId: string, requestDigest: string,
/**
 * Extensible operation label (for example `agent`, `phase`, `checkpoint`).
 */
operation: string, status: WorkflowCallStatus, result: JsonValue | null, error: string | null, startedAt: number | null, completedAt: number | null, };
