// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Immutable identity for one exact workflow source document.
 */
export type WorkflowSourceIdentity = {
/**
 * Human-readable source provenance, such as a path or plugin resource id.
 */
source: string, name: string, version: string,
/**
 * SHA-256 digest of the exact source bytes.
 */
digest: string, };
