// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { WorkflowCallRecord } from "./WorkflowCallRecord";
import type { WorkflowEngine } from "./WorkflowEngine";
import type { WorkflowRunStatus } from "./WorkflowRunStatus";
import type { WorkflowSourceIdentity } from "./WorkflowSourceIdentity";

export type WorkflowRunRecord = { runId: string, workflow: WorkflowSourceIdentity, engine: WorkflowEngine, engineRevision: string, parentThreadId: string,
/**
 * Digest of the canonical start request, including workflow digest and args.
 */
requestDigest: string,
/**
 * Digest of the frozen backend, plugin generation, execution profile, and
 * effective runtime policy selected before this run was admitted.
 */
bindingDigest: string, status: WorkflowRunStatus, result: JsonValue | null, error: string | null, agentsStarted: number, calls: Array<WorkflowCallRecord>, createdAt: number, updatedAt: number, completedAt: number | null, };
