// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDiagnosticLevel } from "./WorkflowDiagnosticLevel";
import type { WorkflowScope } from "./WorkflowScope";

export type WorkflowDiagnostic = { level: WorkflowDiagnosticLevel, code: string, message: string, sourceScope: WorkflowScope | null, sourceId: string | null, path: string | null, };
