// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable state of an accepted workflow run.
 */
export type WorkflowRunStatus = "pendingApproval" | "queued" | "running" | "completed" | "failed" | "cancelled" | "uncertain";
