//! Shell completion is a working command, not a registered placeholder.

use std::fs;
use std::path::Path;
use std::process::Command;

#[cfg(unix)]
use std::ffi::OsStr;

fn zuno() -> Command {
    Command::new(env!("CARGO_BIN_EXE_zuno"))
}

fn isolated_zuno(root: &Path) -> Command {
    let mut command = zuno();
    command
        .env("HOME", root.join("home"))
        .env("USERPROFILE", root.join("home"))
        .env("XDG_CONFIG_HOME", root.join("config"))
        .env("XDG_DATA_HOME", root.join("data"))
        .env("LOCALAPPDATA", root.join("local"));
    command
}

fn run(root: &Path, args: &[&str]) -> std::process::Output {
    isolated_zuno(root)
        .args(args)
        .output()
        .expect("run zuno completion")
}

fn assert_success(output: &std::process::Output) {
    assert!(
        output.status.success(),
        "status: {}\nstdout: {}\nstderr: {}",
        output.status,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn assert_reported_install_path(stdout: &str, expected: &Path) {
    let first_line = stdout
        .lines()
        .next()
        .expect("install result has a path line");
    let (_, reported) = first_line
        .split_once(" completion at ")
        .unwrap_or_else(|| panic!("install result has an unexpected first line: {first_line}"));
    let reported = fs::canonicalize(reported)
        .unwrap_or_else(|error| panic!("canonicalize reported completion path: {error}"));
    let expected = fs::canonicalize(expected)
        .unwrap_or_else(|error| panic!("canonicalize expected completion path: {error}"));
    assert_eq!(reported, expected, "{stdout}");
}

#[test]
fn completion_bash_emits_a_loadable_script() {
    let root = tempfile::tempdir().expect("temporary home");
    let output = run(root.path(), &["completion", "bash"]);
    assert_success(&output);
    let stdout = String::from_utf8(output.stdout).expect("completion output is UTF-8");
    assert!(stdout.contains("_zuno"), "{stdout}");
    assert!(stdout.contains("complete"), "{stdout}");
}

#[test]
fn completion_requires_a_supported_shell() {
    let root = tempfile::tempdir().expect("temporary home");
    let output = isolated_zuno(root.path())
        .arg("completion")
        .output()
        .expect("run zuno completion");

    assert_eq!(output.status.code(), Some(2));
    assert!(
        String::from_utf8_lossy(&output.stderr).contains("<SHELL>"),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
}

#[test]
fn completion_install_uses_deterministic_user_paths_and_preserves_stdout_mode() {
    let root = tempfile::tempdir().expect("temporary home");
    let cases = [
        (
            "bash",
            root.path().join("data/bash-completion/completions/zuno"),
            "bash",
        ),
        (
            "zsh",
            root.path().join("home/.zsh/completions/_zuno"),
            "fpath",
        ),
        (
            "fish",
            root.path().join("config/fish/completions/zuno.fish"),
            "fish",
        ),
        (
            "powershell",
            root.path().join("local/zuno/completions/_zuno.ps1"),
            "dot-source",
        ),
        (
            "elvish",
            root.path().join("config/elvish/lib/zuno.elv"),
            "use zuno",
        ),
    ];

    for (shell, path, activation) in cases {
        let generated = run(root.path(), &["completion", shell]);
        assert_success(&generated);
        assert!(!generated.stdout.is_empty(), "{shell} output was empty");

        let installed = run(root.path(), &["completion", shell, "--install"]);
        assert_success(&installed);
        assert_eq!(
            fs::read(&path).unwrap_or_else(|error| {
                panic!("read installed {} completion: {error}", path.display())
            }),
            generated.stdout,
            "{shell} install did not preserve generated bytes"
        );
        let stdout = String::from_utf8(installed.stdout).expect("install result is UTF-8");
        assert_reported_install_path(&stdout, &path);
        assert!(
            stdout.contains("No shell profile was modified."),
            "{stdout}"
        );
        assert!(stdout.contains("Activation:"), "{stdout}");
        assert!(stdout.contains(activation), "{stdout}");
    }
}

#[test]
fn completion_install_replaces_existing_output_atomically_without_touching_profiles() {
    let root = tempfile::tempdir().expect("temporary home");
    let profile_paths = [
        root.path().join("home/.bashrc"),
        root.path().join("home/.zshrc"),
        root.path().join("config/fish/config.fish"),
        root.path().join("home/Documents/PowerShell/profile.ps1"),
        root.path().join("config/elvish/rc.elv"),
    ];
    for profile in &profile_paths {
        fs::create_dir_all(profile.parent().expect("profile parent")).expect("profile directory");
        fs::write(profile, b"keep this profile unchanged\n").expect("profile fixture");
    }

    let destination = root.path().join("data/bash-completion/completions/zuno");
    fs::create_dir_all(destination.parent().expect("completion parent"))
        .expect("completion directory");
    fs::write(&destination, b"stale completion\n").expect("stale completion");

    let output = run(root.path(), &["completion", "bash", "--install"]);
    assert_success(&output);
    let installed = fs::read(&destination).expect("installed completion");
    assert_ne!(installed, b"stale completion\n");
    assert!(installed.windows(5).any(|window| window == b"_zuno"));

    let entries = fs::read_dir(destination.parent().expect("completion parent"))
        .expect("list completion directory")
        .map(|entry| entry.expect("completion entry").file_name())
        .collect::<Vec<_>>();
    assert_eq!(entries, [destination.file_name().expect("completion name")]);

    for profile in profile_paths {
        assert_eq!(
            fs::read(&profile).expect("unchanged profile"),
            b"keep this profile unchanged\n",
            "{} was modified",
            profile.display()
        );
    }
}

#[test]
fn completion_install_falls_back_to_home_when_platform_roots_are_unset() {
    let root = tempfile::tempdir().expect("temporary home");
    let home = root.path().join("home");
    let cases = [
        (
            "bash",
            home.join(".local/share/bash-completion/completions/zuno"),
        ),
        ("fish", home.join(".config/fish/completions/zuno.fish")),
        (
            "powershell",
            home.join(".local/share/zuno/completions/_zuno.ps1"),
        ),
        ("elvish", home.join(".config/elvish/lib/zuno.elv")),
    ];

    for (shell, path) in cases {
        let output = zuno()
            .args(["completion", shell, "--install"])
            .env("HOME", &home)
            .env("USERPROFILE", &home)
            .env_remove("XDG_CONFIG_HOME")
            .env_remove("XDG_DATA_HOME")
            .env_remove("LOCALAPPDATA")
            .output()
            .expect("run zuno completion install with HOME fallback");
        assert_success(&output);
        assert!(path.is_file(), "{} was not installed", path.display());
    }
}

#[cfg(unix)]
#[test]
fn completion_install_accepts_non_utf8_xdg_paths() {
    use std::os::unix::ffi::OsStringExt as _;

    let root = tempfile::tempdir().expect("temporary home");
    let data = root
        .path()
        .join(std::ffi::OsString::from_vec(b"data-\xff".to_vec()));
    let mut command = isolated_zuno(root.path());
    let output = command
        .args(["completion", "bash", "--install"])
        .env(OsStr::new("XDG_DATA_HOME"), &data)
        .output()
        .expect("run zuno completion with non-UTF-8 XDG_DATA_HOME");
    assert_success(&output);
    assert!(
        data.join("bash-completion/completions/zuno").is_file(),
        "completion was not installed below the non-UTF-8 path"
    );
}
