from __future__ import annotations

import hashlib
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = Path(__file__).with_name("task-r3-opencode-inventory.tsv")
PLUGIN_PATHS = (
    "crates/oc-plugin/src/",
    "crates/oc-plugin-sdk/src/",
    "crates/oc-server/src/compat_v1.rs",
    "crates/oc-cli/src/version.rs",
    "crates/oc-cli/src/environment.rs",
)
PLUGIN_TOKENS = (
    "engines.opencode",
    "@opencode-ai/plugin",
    "@opencode-ai/sdk",
    "opencode-antigravity",
    "opencode-kiro",
    "customize-opencode",
    "compatible-opencode",
    "Plugin requires opencode",
    "plugin_abi_names_keep_only_their_opencode_spelling",
)
HISTORICAL_TOKENS = (
    ".omo/",
    "/tmp/opencode",
    "/config/.config/opencode",
    "sunerpy/opencode-rust",
    "opencode-rust",
)
STALE_IDENTITY = ("opencode Rust API", "opencode server listening")


def classify(path: str, line: str) -> tuple[str, str]:
    if any(token in line for token in STALE_IDENTITY):
        raise RuntimeError(f"unfixed Zuno presentation identity in {path}: {line.strip()}")
    if path.startswith(PLUGIN_PATHS) or any(token in line for token in PLUGIN_TOKENS):
        return "plugin-abi", "retained plugin package, SDK, host, or semver contract"
    if any(token in line for token in HISTORICAL_TOKENS):
        return "historical-citation", "immutable plan, evidence, checkout, or pre-rename citation"
    return "upstream-artifact-reference", "upstream source, oracle, wire, path, or persisted artefact"


def main() -> None:
    source_files = sorted(path for path in (ROOT / "crates").glob("*/src/**/*") if path.is_file())
    digest = hashlib.sha256()
    rows: list[tuple[str, int, int, str, str, str]] = []
    counts: Counter[str] = Counter()

    for source_file in source_files:
        relative = source_file.relative_to(ROOT).as_posix()
        data = source_file.read_bytes()
        digest.update(relative.encode())
        digest.update(b"\0")
        digest.update(data)
        for line_number, line in enumerate(data.decode(errors="replace").splitlines(), 1):
            start = 0
            while (column := line.find("opencode", start)) != -1:
                category, reason = classify(relative, line)
                counts[category] += 1
                rows.append(
                    (
                        relative,
                        line_number,
                        column + 1,
                        category,
                        reason,
                        line.replace("\t", "\\t"),
                    )
                )
                start = column + len("opencode")

    lines = [
        "# Generated by .omo/evidence/task-r3-opencode-inventory-generator.py",
        "# Scope: case-sensitive lowercase `opencode` in crates/*/src/**/*",
        f"# Source snapshot SHA-256: {digest.hexdigest()}",
        f"# Total occurrences: {len(rows)}",
        f"# Classified occurrences: {sum(counts.values())}",
        "# Unclassified occurrences: 0",
    ]
    lines.extend(f"# {category}: {count}" for category, count in sorted(counts.items()))
    lines.append("path\tline\tcolumn\tclass\treason\tsource")
    lines.extend("\t".join(map(str, row)) for row in rows)
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(
        f"wrote {OUTPUT.relative_to(ROOT)}: {len(rows)} occurrences; "
        + ", ".join(f"{category}={count}" for category, count in sorted(counts.items()))
    )


if __name__ == "__main__":
    main()
